### ISSUE TITLE
Colors not applied to DM column unreads

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#1]
## ![screenshot from 2016-06-25 10-29-49](https://cloud.githubusercontent.com/assets/9281956/16357571/0b887776-3ac0-11e6-8591-e26704e93ad1.png)

![screenshot from 2016-06-25 10-30-12](https://cloud.githubusercontent.com/assets/9281956/16357572/0f6aa6a2-3ac0-11e6-8216-09753e7aed2c.png)

**Comment by ciolt** [comment]
Thanks for letting me know, it's fixed now. 
![image](https://cloud.githubusercontent.com/assets/5000732/16358240/e92f85ae-3adb-11e6-952c-7754ac73458e.png)
