### ISSUE TITLE
tweetdeck settings tabs are messed up

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#13]
![screenshot from 2016-06-26 23-23-21](https://cloud.githubusercontent.com/assets/9281956/16368554/05ffe0ec-3bf5-11e6-89b2-e366d003f6eb.png)

**Comment by ciolt** [comment]
Are you sure that you synced the GitHub repository with your local repo?
I've tried the extension with my own Chrome Dev build and Chrome Canary, and it doesn't appear there.

I've even tried with this ancient Netscape-era "browser" and it looks fine.

![image](https://cloud.githubusercontent.com/assets/5000732/16368739/d5a063da-3bff-11e6-966b-a2e0dd161c91.png)

**Comment by ciolt** [comment]
this is invalid, mate

**Comment by ashkitten** [comment]
It only occurs when using the dark theme. Still there.

**Comment by ashkitten** [comment]
![screenshot from 2016-06-27 16-17-43](https://cloud.githubusercontent.com/assets/9281956/16396103/b4a0e7ee-3c82-11e6-888b-f000097533a4.png)
![screenshot from 2016-06-27 16-17-32](https://cloud.githubusercontent.com/assets/9281956/16396104/b4b38d5e-3c82-11e6-92b4-1cc20bfd71d3.png)
