### ISSUE TITLE
settings tabs overflow

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#2]
![screenshot from 2016-06-26 00-13-40](https://cloud.githubusercontent.com/assets/9281956/16360648/f3fb77c0-3b32-11e6-9f7a-ae6b4fd8ae0d.png)

**Comment by ciolt** [comment]
Keep them coming!

![image](https://cloud.githubusercontent.com/assets/5000732/16361059/73cc26cc-3b4f-11e6-9c6e-a3b3d3da6d7c.png)
