### ISSUE TITLE
Tweet action buttons displayed above image preview when using large previews

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#24]
![screenshot from 2016-06-27 15-33-51](https://cloud.githubusercontent.com/assets/9281956/16394798/a2346686-3c7c-11e6-861d-dcf45ed01fe8.png)

**Comment by ciolt** [comment]
This can't be changed due to the way large previews work in TweetDeck.
The tweet content and buttons are merged, while the image preview goes outside the box containing the tweet.

The only way to fix it would be to use some horrifyingly disgusting and messy hack, but I'm not doing that.
