### ISSUE TITLE
default theme + light breaks shit

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#28]
![screenshot from 2016-06-27 16-20-43](https://cloud.githubusercontent.com/assets/9281956/16396197/36bf2308-3c83-11e6-93ea-b8efdd69b6e0.png)

**Comment by ciolt** [comment]
That's because the "default theme" doesn't exist.

![image](https://cloud.githubusercontent.com/assets/5000732/16396842/c6ddb7a0-3c8e-11e6-9cfd-55b90811235b.png)
