### ISSUE TITLE
gradients have no place here

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#31]
![screenshot from 2016-06-27 18-56-41](https://cloud.githubusercontent.com/assets/9281956/16399570/55d4c34a-3c99-11e6-8c9a-a5b2f06d7fd8.png)

**Comment by ciolt** [comment]
It will vanish soon.

but

That header is a nice piece of design right there that you only find on Behance.

**Comment by ciolt** [comment]
You could always open a pull request, you know :P

**Comment by ashkitten** [comment]
@ciolt That requires creating and maintaining my own fork which is way too much work. I'm not doin that shit.

**Comment by ciolt** [comment]
> @ciolt That requires creating and maintaining my own fork which is way too much work. I'm not doin that shit.

it requires this:
- fork repository
- clone
- make changes
- push
- open pull request

simple, noob

**Comment by ashkitten** [comment]
but then what happens to the fork after that specific PR? if i want to use it again i've got to keep it up to date which can be a real ass.

**Comment by ciolt** [comment]
![image](https://cloud.githubusercontent.com/assets/5000732/16401190/7988df1c-3cb0-11e6-9c7f-fa722bf900cc.png)
![image](https://cloud.githubusercontent.com/assets/5000732/16401196/83dcbf1a-3cb0-11e6-8990-c10b6e9329fd.png)
![image](https://cloud.githubusercontent.com/assets/5000732/16401203/97c38888-3cb0-11e6-90d8-298b9c0f50bf.png)

**Comment by ashkitten** [comment]
ughhhhh

fine

**Comment by ciolt** [comment]
I can also un-fork this project and make it my own, as well

but then I won't be able to leech off of ModernDeck's updates :(
