### ISSUE TITLE
DM unread count in sidebar is messed up

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#7]
![screenshot from 2016-06-26 23-10-52](https://cloud.githubusercontent.com/assets/9281956/16368366/4087441e-3bf3-11e6-9572-6ce8cede9763.png)

also, it appears for a few seconds if you use the sidebar buttons to quickscroll to a column which is kinda weird

**Comment by ciolt** [comment]
done

![image](https://cloud.githubusercontent.com/assets/5000732/16371122/859e35a2-3c12-11e6-8c97-b02892164f8c.png)
