### ISSUE TITLE
unread quick scroll to top button appears sporadically

### ISSUE THREAD

**Issue by ashkitten** [ciolt/ModernDeck#8]
not actually sure what circumstances cause the behavior, but it happens every now and then even when there are no new tweets in the column to scroll to

**Comment by ciolt** [comment]
Can you explain a little further?

**Comment by ashkitten** [comment]
okay so you know this thing?
![screenshot from 2016-06-27 15-19-13](https://cloud.githubusercontent.com/assets/9281956/16394386/8bd92fd6-3c7a-11e6-8bef-90f811779157.png)
sometimes it pops up randomly with like 21 new tweets or whatever, even if there aren't actually any which is really weird. i think it may have something to do with switching tabs away from moderndeck but not sure.

**Comment by ciolt** [comment]
That's a TweetDeck problem, it happens on the stock version too. Lots of people don't like it when it does that, there's even extensions made specifically to block that thing from popping up.
